call addAdministrador('01267688114', 'Rodrigo Siqueira', 'rodriados@gmail.com', '36221920', '123');
call addAdministrador('00159322146', 'Marcos Iseki', 'marcos@gmail.com', '36221821', '123');

call addSecretario('41119570808', '00159322146', 'Mariana Caravanti', 'mariana@gmail.com', '31177114', '123');
call addSecretario('76259570808', '01267688114', 'Nathalia Zenerato', 'nathalia@gmail.com', '32837114', '123');
call addSecretario('28379570808', '00159322146', 'Nicolas Santos', 'nicolas@gmail.com', '32838736', '123');

call addProfessor('63527363527', '01267688114', 'Maria Istela', 'mariaistela@gmail.com', '63527253', '123', 'Doutor');
call addProfessor('73274626362', '00159322146', 'Edna Hoshino', 'edna@gmail.com', '52435243', '123', 'Doutor');
call addProfessor('83746336574', '00159322146', 'Wellynnson Fabaio', 'fabaio@gmail.com', '63546353', '123', 'Mestre');
call addProfessor('62736625588', '01267688114', 'Edson Takashi', 'takashi@gmail.com', '65346353', '123', 'Doutor');
call addProfessor('63726325619', '00159322146', 'Edson Caceres', 'caceres@gmail.com', '26532376', '123', 'Doutor');
call addProfessor('62839473625', '01267688114', 'Hana Montana', 'montana@gmail.com', '36272536', '123', 'Doutor');
call addProfessor('26736215625', '00159322146', 'Roberto Oliveira', 'roberto@gmail.com', '76342635', '123', 'Mestre');
call addProfessor('26372671873', '00159322146', 'Tokuda', 'tokuda@gmail.com', '73647362', '123', 'Doutor');
call addProfessor('38463263884', '01267688114', 'Maura Candolo', 'maura@gmail.com', '26327263', '123', 'Doutor');
call addProfessor('26571526151', '00159322146', 'Paulo Pagliosa', 'pagliosa@gmail.com', '73643625', '123', 'Doutor');
call addProfessor('27398722222', '01267688114', 'Carlos Higa', 'higa@gmail.com', '52436253', '123', 'Doutor');
call addProfessor('26372565666', '01267688114', 'Eloi Araujo', 'eloi@gmail.com', '26532451', '123', 'Doutor');

call addAluno('72362723627', '00159322146', 'Thiago Ikeda', 'thiago@gmail.com', '36273625', '123', 'Fri Nov 07 12:37:05 AMST 2015');
call addAluno('26376235625', '01267688114', 'Guilherme Terenciani', 'guilherme@gmail', '52432543', '123', '2015-12-01');
call addAluno('27267362222', '01267688114', 'Jainor Souza', 'jainor@gmail.com', '26532459', '123', '2015-12-01');
call addAluno('92803920398', '00159322146', 'Diego Cintra', 'diego@gmail.com', '26532480', '123', '2016-12-01');
call addAluno('15261562511', '00159322146', 'Aimee Calepso', 'aimee@gmail.com', '26532481', '123', '2017-12-01');
call addAluno('14251425154', '00159322146', 'Rodrigo Emboava', 'rodrigo@gmail.com', '26532482', '123', '2015-12-01');
call addAluno('25621562514', '01267688114', 'Sarah Lima', 'sarah@gmail.com', '26532483', '123', '2015-12-01');
call addAluno('62625512112', '00159322146', 'Rogerio Sandim', 'rogerio@gmail.com', '26532484', '123', '2017-12-01');
call addAluno('83748734873', '01267688114', 'Angelica Leite', 'angelica@gmail.com', '26532485', '123', '2016-12-01');
call addAluno('90239029390', '01267688114', 'Aryane Souza', 'aryane@gmail.com', '26532486', '123', '2016-12-01');
call addAluno('28392839288', '01267688114', 'Maria Silva', 'maria@gmail.com', '26532487', '123', '2015-12-01');
call addAluno('38383625254', '00159322146', 'Fabiola Ramoa', 'fabiola@gmail.com', '26532488', '123', '2014-12-01');


call addLivro('DSL: Linguagens Específicas de Domínio', '1', '1', '2012', 'Martin Fowler', 'Quando cuidadosamente selecionadas e usadas, as Linguagens Específicas de Domínio (DSLs) podem simplificar código complexo, promover uma comunicação eficaz com os clientes, melhorar a produtividade e remover gargalos no desenvolvimento. 

Martin Fowler fornece as informações que os profissionais de software precisam para decidir se e quando usarão DSLs, apresentando técnicas eficazes para construí-las e guiando os engenheiros de software na escolha das abordagens corretas para suas aplicações. ', '1', '9788540702127', 'Bookman');

call addLivro('Desmistificando Algoritmos', '1', '1', '2013', 'Thomas H. Cormen', 'Alguma vez você já se perguntou como seu GPS pode encontrar o caminho mais rápido para o seu destino, selecionando uma rota entre inúmeras possibilidades em poucos segundos? Ou como o seu número de cartão de crédito é protegido quando você faz uma compra pela internet? E como essas formulações matemáticas traduzem-se em seu GPS, seu laptop ou seu smartphone? A resposta é: algoritmos. Thomas Cormen, co-autor do principal livro-texto sobre o assunto, explica de forma extremamente didática o que são algoritmos, como descrevê-los e avaliá-los; como procurar informações em um computador e métodos para reorganizar as informações em uma ordem prescrita ("triagem"); como resolver os problemas básicos que podem ser modelados em um computador com uma estrutura matemática chamada de ¿gráfico¿ (útil para modelagem de redes de estradas, dependências entre tarefas, e as relações financeiras); como resolver os problemas sobre cadeias de caracteres, tais como estruturas de DNA, e os princípios básicos por trás da criptografia; fundamentos de compressão de dados entre outros pontos. 
', '1', '9788535271775', 'ST');

call addLivro('HTML 5 - A Linguagem de Marcação que Revolucionou a Web', '1', '1', '2011', 'Maurício Samy Silva', 'HTML5 é a linguagem de marcação que amplia de forma surpreendente as funcionalidades da HTML, alterando de maneira significativa como você desenvolve para a web. Trata-se da mais extensa especificação para a HTML focada em criar funcionalidades para desenvolvimento não só de sites, mas também de aplicações de internet rica (RIA). 

A obra aborda as funcionalidades da HTML5, de forma clara, em linguagem didática, mostrando vários exemplos práticos. 

A utilização de marcação HTML5 possibilita ao autor web alcançar os seguintes objetivos: 

- Criar um código totalmente semântico empregando os novos elementos da linguagem ou mesmo os elementos já existentes que tiveram sua semântica redefinida; 
- Usar os novos atributos da linguagem para criar elementos gráficos ricos no desenvolvimento de aplicações web; 
- Inserir mídia, tais como áudio e vídeo e a funcionalidade canvas de uma forma nativa, sem dependência de plugins de terceiros ou extensões proprietárias; 
- Desenvolver formulários altamente interativos com validação no lado do cliente com uso de atributos criados especialmente para essas finalidades; 
- Usar as API Geolocation, Web Storage, Web Messaging, Web Sockets e Web Workers; 
- Usar mecanismos, como Microdados e, ARIA para incrementar a acessibilidade. ', '1', '9788575222614', 'Novatec');

call addLivro('Introdução a Sistemas de Bancos de Dados', '8', '1', '2004', 'C. J. Date', 'Introdução a Sistemas de Bancos de Dados, Oitava Edição, oferece uma introdução completa ao vasto campo de sistemas de bancos de dados. O livro apresenta uma base sólida sobre os alicerces da tecnologia de bancos de dados, ao mesmo tempo em que esclarece como o campo deve se desenvolver no futuro. Esta nova edição foi revista e atualizada com as tendências e desenvolvimentos dos sistemas de bancos de dados.
Este livro aborda os seguintes assuntos: Visão geral do gerenciamento de bancos de dados, Arquitetura de sistemas de bancos de dados, Introdução aos bancos de dados relacionais, Introdução à SQL, Tipos, Relações. Cálculo relacional, Integridade, Visões, Dependências funcionais, Normalização avançada, Modelagem semântica, Recuperação, Concorrência, Segurança, Otimização, Falta de informações, Herança de tipo, Bancos de dados distribuídos, Apoio à decisão, Sistemas baseados em lógica, Sistemas baseados em lógica, Bancos de dados relacional/objeto, A World Wide Web e XML.', '2', '8535212736', 'Campus');

call addLivro('Sistema de Banco de Dados', '6', '1', '2012', 'Abraham Silberschatz, Henry F. Korth, S. Sudarshan', 'Este é um livro-texto clássico sobre treinamento em banco de dados. A obra apresenta os conceitos fundamentais do gerenciamento de banco de dados de uma maneira intuitiva e motivadora para os alunos, inclusive com um novo exemplo de banco de dados de uma universidade, que ilustra escolhas mais complexas de projeto. O texto enfatiza questões práticas, aplicações e implementação, junto com uma cobertura dos principais conceitos teóricos.

Nesta 6ª edição, todos os capítulos foram revisados para refletir os avanços mais recentes na tecnologia. Os autores fizeram ainda uma cobertura revisada e expandida dos seguintes temas: Variantes da SQL em sistemas reais; Projeto relacional; Aplicações Web e segurança; Indexação e otimização de consulta; Gerenciamento de transação; Bancos de dados paralelos e distribuídos.', '2', '9788535245356', 'Campus');

call addLivro('Organização e Projeto de Computadores: A Interface Hardware/Software ', '1', '1', '2013', 'David A. Patterson, John L. Hennessy', 'Este livro apresenta conceitos que são a base para os computadores atuais, destacando os tópicos de interface de hardware e software. Com foco na mudança revolucionária de computação sequencial para paralela, Organização e Projeto de Computadores aborda o surgimento e a importância da GPU moderna, descrevendo em detalhes o multicore microprocessador, altamente otimizado para vários segmentos da computação visual. Além do enfoque em paralelismo, esta tradução da 4ª edição revista e atualizada oferece conteúdos em Flash de memória e máquinas virtuais, bem como um conjunto completo de exercícios sugeridos por professores e alunos. Os temas abordados e os exercícios presentes no final da cada capítulo tornam este livro adequado tanto para aqueles com pouca experiência na área, mas que precisam entender a organização básica do computador, quanto para aqueles que já possuem uma base em linguagem assembly e projeto lógico e desejam aprender a projetar um computador ou entender como e porquê um sistema funciona de determinada forma.', '1', '9788535235852', 'ST');

call addLivro('Inteligência Artificial', '3', '1', '2013', 'Stuart Russel, Peter Norvig', 'Número um no seu campo, este livro oferece a mais abrangente introdução à teoria e prática da inteligência artificial, sendo adotado por mais de 600 universidades de 60 países. 

Nos últimos cinquenta anos de pesquisas sobre IA e nos dois últimos milênios de trabalhos relacionados a esse tema, muitas ideias surgiram e a maneira como se pensa esta área está em constante evolução. Nesta tradução da terceira edição, foram consideradas as mais importantes aplicações de tecnologia de IA e seus marcos algoritmos, como a solução do jogo de damas, colocando a obra num patamar teórico bastante consistente. 

Inteligência Artificial destina-se, principalmente, ao uso em cursos de graduação ou de extensão. Também pode ser usado em cursos de pós-graduação ou para quaisquer estudantes que tenham familiaridade com os conceitos básicos de ciência da computação. ', '2', '9788535237016', 'Campus');

call addLivro('Garantia Da Qualidade De Software', '1', '1', '2002', ' ', 'Totalmente alinhado com as mais modernas metodologias existentes no mercado,(RUP - Rational Unified Process; CMM - Capability Maturity Model, SWEBOK - Software Engineering Body of Knowledge e PMI ? Project Management Institute)este livro coloca você diante dos conceitos mais avançados sobre como aplicar um ?Processo de Garantia da Qualidade de Software? na sua empresa. Usando uma abordagem simplificada e de fácil de entendimento, possibilita aos leitores assimilar gradualmente os aspectos mais relevantes envolvidos na implantação de um ?Processo de Garantia da Qualidade de Software?. Estabelece uma visão corporativa de qualidade de software e prepara a organização ao desafio de incorporar estes conceitos no seu dia-a-dia. Combinando visão acadêmica com realidade empresarial, o livro apresenta um modelo metodológico viável tanto para as organizações que nunca iniciaram um SPI (Software Process Improvement) quanto às organizações que buscam atingir os níveis CMM 2 e 3. A busca pela viabilidade na aplicação das melhores práticas voltadas à garantia da qualidade de software torna este livro uma peça-chave para fazer uma verdadeira revolução na sua organização.', '1', '8535211241', 'Campus');

call addLivro('Análise e Projeto de Sistemas de Informação Orientados a Objetos', '2', '1', '2010', 'Raul Sidnei Wazlawick', 'Este livro apresenta, de maneira didática e aprofundada, elementos de análise e projeto de sistemas de informação orientados a objetos. Seu conteúdo diferencia-se da maioria dos outros livros na área por apresentar em detalhes as técnicas de construção de contratos de operação e consulta de sistema de forma que possam ser usados para efetiva geração de código. Nesta 2ª edição, novos padrões e técnicas de modelagem conceitual são detalhadamente apresentados, técnicas estas também adequadas para uso com contratos e diagramas de comunicação, de forma a garantir geração automática de código; não apenas de esqueletos, mas de código final executável.

Para que a obra pudesse aprofundar ainda mais as informações sobre análise e projeto orientados a objetos sem se tornar demasiadamente longo, foram suprimidas nesta segunda edição algumas informações referentes ao processo de engenharia de software, que estavam presentes na primeira edição. Além disso, para ganhar dinamismo, cada exemplar da obra traz um código individual (PIN) por meio do qual o leitor poderá acessar no site da editora (www.elsevier.com.br) slides e exercícios referentes a cada capítulo.', '3', '9788535239164', 'Campus');

call addLivro('Otimização combinatória e programação linear', '1', '1', '2005', 'autores', 'Esta obra tem por objetivo propiciar subsídios técnicos, descrever modelos matemáticos, debater algoritmos de solução e sugerir temas de aplicação, dentro da visão quantitativa de análise do fenômeno de tomada de decisão, principalmente aos alunos de graduação das engenharias, cursos de administração e de ciência da computação. O conteúdo programático coberto pelos capítulos 1 a 5 engloba o que é exigido em disciplinas como ?Pesquisa Operacional?, ?Otimização de Sistemas de Engenharia?, ?Programação Linear? e outras. O conteúdo dos capítulos 6 a 10 aborda temas que são objeto de disciplinas como ?Otimização Combinatória?, ?Algoritmos em Grafos?, ?Fluxos em Redes?, entre outras. Essa segunda parte do livro contém material um pouco mais avançado, servindo a disciplinas optativas de nossos cursos de graduação ou a disciplinas de pós-graduação. 
Uma outra característica marcante deste trabalho são as várias aplicações práticas retiradas da realidade brasileira, o que permite aproximar a disciplina ao dia-a-dia do estudante, aumentando o incentivo à motivação. No âmbito da programação linear, o livro é caracterizado pelo uso intensivo de interpretação econômica do método simplex e das relações de dualidade e sensibilidade. A idéia é lembrar que as ferramentas de otimização indicam as atividades de maior produtividade nas empresas e que o uso dessas ferramentas também indica os preços de maior competitividade. 
No âmbito da otimização combinatória, como o próprio nome indica, o livro se caracteriza pela apresentação dos problemas através do uso deliberado de formulações de programação linear inteira mista. Além do interesse teórico, a formulação de problemas combinatórios através da programação inteira abre caminho para o uso dos eficientes pacotes comerciais de programação matemática, cujo avanço na solução exata de importantes problemas práticos tem sido marcante. Mesmo para heurísticas que dispensam a formulação de programação linear inteira, muitas vezes podem ser feitas avaliações de qualidade de solução mediante o uso de relaxação do problema de programação linear. 
Constituindo uma versão atualizada que preserva o conteúdo original e melhora a forma de apresentação, esta segunda edição contempla uma significativa inclusão de referências à produção científica do primeiro lustre do novo milênio. A atualização resultou em um saldo positivo de dezenas de páginas, com a supressão de algumas páginas do apêndice que não eram referenciadas no texto principal da primeira edição. A rica ilustração do livro foi reorganizada com a numeração restrita ao escopo de cada capítulo, abrangendo as referências a figuras, equações, quadros e tabelas, que, por sua vez, tiveram apresentação padronizada. Esta segunda edição surge numa época em que se consolida a ligação entre otimização combinatória e programação linear, o que ratifica o acerto do nome do livro e a importância da matéria nele ensinada.', '2', '8535215204', 'Campus');

call addLivro('Redes e Sistemas de Comunicação de Dados', '1', '1', '2005', 'William Stallings', 'Reúne o que há de mais avançado em Redes de Computadores, a interface com Telecomunicações e Sistemas de Gerenciamento de Dados Empresariais. Descrição. Este livro aborda detalhadamente os fundamentos de comunicação de dados, essenciais para o gerenciamento de negócios e de informação. O livro foi estruturado para atender às necessidades dos cursos de Computação e público profissional.', '1', '8535217312', 'Campus');

call addLivro('Programação Assembly', '6', '1', '2012', 'Jo´se Augusto N. G. Manzano', 'Assembly é uma linguagem utilizada para programar computadores em baixo nível. Seus princípios e recursos encontram-se neste livro, voltado aos iniciantes no estudo dessa linguagem, o qual transmite conhecimentos básicos da programação de microcomputadores IBM-PC a partir do microprocessador Intel 8086/8088, cuja escolha se deu por ser a versão mais difundida em escolas do mundo todo e, ainda, em razão de a ferramenta Emu8086 v. 4.08 empregar o padrão Intel 8086/8088, que possui grande quantidade de ferramentas de simulação e de programação, sendo o ambiente Emu8086 uma delas. Outro detalhe a ser considerado é o fato de ficar um pouco mais fácil entender a engenharia de um microprocessador de 32 bits (ou mesmo de 64 bits, lançamento inicial da empresa AMD) a partir do modelo 8086 do que a partir dos modelos 8080 e 8085, pois foi com o modelo 8086 que a Intel obteve grande habilidade técnica para resolver problemas de endereçamento de memória e deu a ela toda a base para chegar à capacidade de 32 bits e, posteriormente, a 64 bits. A sexta edição, revisada, atualizada e ampliada, do livro Fundamentos em Programação Assembly para Computadores IBM-PC a partir dos Microprocessadores Intel 8086/8088 implementa os opcodes dos códigos Assembly dos capítulos 3 a 5, visando uma forma mais clara de expor o assunto, e o capítulo 7 aprimora os procedimentos NEAR (próximo) e FAR (distante). O novo apêndice C aborda a ferramenta para debug GRDB (Get Real DeBugger), com capacidade de operação em registradores de 32 bits, e o uso do programa DEBUG do professor Paul Vojta em modo 32 bits. O capítulo 11, outra novidade desta edição, descreve de maneira simples como implementar tomadas de decisão e laços para repetição a partir da óptica de alto nível.', '1', '9788536504261', 'Érica');

call addLivro('Fundamentos de Sistemas Operacionais', '8', '1', '2010', 'Abraham Silberschatz', 'Sistemas operacionais de fonte aberta, máquinas virtuais e computação em clusters estão entre os principais campos dos sistemas operacionais e redes que estão mudando rapidamente. Com revisões significativas e alterações na organização, o livro permanece atual e relevante, ajudando o estudante a dominar os conceitos fundamentais dos sistemas operacionais preparando-o ao mesmo tempo para os desenvolvimentos surgidos no mundo atual. 

Esta edição explica o que são sistemas operacionais, o que eles fazem e como são projetados e construídos; gerenciamento de processos, de memória e de armazenamento; proteção e segurança; sistemas distribuídos; e sistemas de uso específico. 

Além dos aspectos básicos, esta nova edição contém revisões significativas e alterações na organização, trazendo as últimas novidades em sistemas operacionais de fonte aberta, processadores multi-core, computadores agrupados, máquinas virtuais, memória transacional, NUMA, gerenciamento de memória no Solaris 10, sistema de arquivos ZFS da Sun e muito mais. 

Um atrativo a mais é o uso de um simulador para a demonstração dinâmica de vários tópicos sobre sistemas operacionais - e o estudante encontrará muitos outros recursos e material de apoio no site da editora LTC. ', '2', '9788521617471', 'LTC');





call addDissertacao('Problemas de corte com sobras aproveitáveis e eliminação de simetrias', '1', '1', '2012', 'Abrantes, Ricardo Luiz de Andrade', 'No presente trabalho estudamos duas variações do problema de empacotamento de itens retangulares idênticos, permitindo rotações de 90 graus, em um poliedro. Uma variação consiste em encontrar a maior quantidade de itens retangulares idênticos que podem ser empacotados em um poliedro. A outra consiste em encontrar o poliedro de um determinado tipo com menor área para empacotar uma quantidade fixa de itens retangulares idênticos. Desenvolvemos restrições de eliminação de simetrias para estes problemas, o que tornou a resolução dos mesmos mais eficiente, por métodos do tipo branch-&-bound. Estudamos também o problema de corte no qual há uma determinada demanda (de itens) a ser cortada e um conjunto de objetos disponíveis. Desejamos satisfazer a demanda minimizando o custo dos objetos utilizados e, dentre as diferentes possibilidades de se fazer isso, desejamos aquela que maximize as sobras aproveitáveis. De forma geral, sobras aproveitáveis podem ser entendidas como regiões retangulares de um objeto que possuem altura e largura iguais ou superiores a de um item de referência e representam sobras do processo de corte que podem se tornar objetos e serem reaproveitadas em um novo procedimento de corte. Apresentamos modelos de otimização em dois níveis para duas variações do problema de corte com sobras aproveitáveis a saber: o problema de corte de itens retangulares em dois estágios e o problema de corte de itens retangulares não guilhotinado. Como formas de resolver os modelos propostos, apresentamos reformulações destes modelos de programação em dois níveis em modelos de programação inteira mista. Lidamos também com uma variação do problema de corte com sobras aproveitáveis considerando a minimização da quantidade de sobras. Aplicamos restrições de eliminação de simetrias aos modelos desenvolvidos para o problema de corte de itens retangulares com sobras aproveitáveis, a fim de resolver instâncias maiores, e desenvolvemos uma estratégia de solução alternativa para os modelos. Os modelos desenvolvidos foram implementados computacionalmente e fomos capazes de resolver instâncias pequenas dos problemas em questão.', '1', 'Birgin, Ernesto Julian Goldberg', 'eliminação de simetrias, otimização, problemas de corte de estoque, problemas de empacotamento, sobras aproveitáveis', 'Ciência da Computação');

call addDissertacao('Ferramentas de auxílio ao seqüenciamento de DNA por montagem de fragmentos: um estudo comparativo', '1', '1', '2000', 'Said Sadique Adi', 'Atualmente, existe um grande número de ferramentas para montagem de fragmentos de DNA disponíveis. Neste trabalho apresentamos um estudo comparativo das ferramentas CAP2, FAKtory, TIGR e PHRAP. Para realizarmos este estudo, primeiramente executamos esses sistemas de montagem sobre 12 casos de testes distintos. Após isso, tomamos os resultados obtidos por cada um deles e os comparamos com as seqüências de onde os fragmentos foram originalmente obtidos. Os testes utilizados avaliam a eficiências dos programas com relação a três problemas associados ao processo de montagem (erros no sequenciamento, fragmentos quimeras e regiões repetidas) e pudemos ver que nenhum dos sistemas é claramente superior aos demais no tratamento de todos eles. Cada ferramenta de montagem parece tratar de melhor forma um problema em especial.Além de avaliarmos os resultados, realizamos também um estudo.', '1', 'Ferreira, Carlos Eduardo', 'biologia computacional, DNA, montagem de fragmentos', 'Ciência da Computação');

call addDissertacao('Tutor inteligente adaptável conforme as preferências do aprendiz', '1', '1', '2003', 'POZZEBON, E.', 'blablablablablablablablabalb, tensotensotensotensotensotensotenostenosnoteonsontsaonoasnlas~dansfdslfkdsfksdFksdfçl, ok', '1', 'Jorge  Muniz Barreto', 'blablabl', 'Ciencia da Computacao');

call addDissertacao('Alinhamentos e comparação de sequências', '1', '1', '2012', 'Araujo, Francisco Eloi Soares de', 'A comparação de sequências finitas é uma ferramenta que é utilizada para a solução de problemas em várias áreas. Comparamos sequências inferindo quais são as operações de edição de substituição, inserção e remoção de símbolos que transformam uma sequência em uma outra. As matrizes de pontuação são estruturas largamente utilizadas e que definem um custo para cada tipo de operação de edição. Uma matriz de pontuação G é indexada pelos símbolos do alfabeto. A entrada de G na linha A, coluna B mede o custo da operação de edição para substituir o símbolo A pelo símbolo B. As matrizes de pontuação induzem funções que atribuem uma pontuação para um conjunto de operações de edição. Algumas dessas funções para a comparação de duas e de várias sequências são estudadas nesta tese. Quando cada símbolo de cada sequência é editado exatamente uma vez para transformar uma sequência em outra, o conjunto de operações de edição pode ser representado por uma estrutura conhecida por alinhamento. Descrevemos uma estrutura para representar o conjunto de operações de edição que não pode ser representado por um alinhamento convencional e descrevemos um algoritmo para encontrar a pontuação de uma sequência ótima de operações de edição usando um algoritmo conhecido para encontrar a pontuação de um alinhamento convencional ótimo. Considerando três diferentes funções induzidas de pontuação, caracterizamos, para cada uma delas, a classe das matrizes para as quais as funções induzidas de pontuação são métricas nas sequências. Dadas duas matrizes de pontuação G e G, dizemos que elas são equivalentes para uma dada função que é induzida por uma matriz de pontuação e que avalia a qualidade de um alinhamento se, para quaisquer dois alinhamentos A e B, vale o seguinte: o alinhamento A é ``melhor'' do que o alinhamento B considerando a matriz G se e somente se A é ``melhor'' do que o alinhamento B considerando a matriz G. Neste trabalho, determinamos condições necessárias e suficientes para que duas matrizes de pontuação sejam equivalentes. Finalmente, definimos três novos critérios para pontuar alinhamentos de várias sequências. Todos os critérios consideram o comprimento do alinhamento além das operações de edição por ele representadas. Para cada um dos critérios definidos,propomos um algoritmo e o problema de decisão correspondente mostramos ser NP-completo.', '1', 'Soares, Jose Augusto Ramos', 'alinhamento de sequência, alinhamento, estendido, custo normalizado de alinhamentos, distância de edição, matrizes equivalentes, métrica', 'Ciência da Computação');

call addDissertacao('Extração de aleatoriedade a partir de fontes defeituosas', '1', '1', '2007', 'Dellamonica Junior, Domingos', 'Recentemente, Barak et al. (2004) exibiram construções de extratores e dispersores determinísticos (funções computáveis em tempo polinomial) com parâmetros melhores do que era anteriormente possível. Introduziremos os conceitos envolvidos em tal trabalho e mencionaremos suas aplicações; em particular, veremos como é possível obter cotas muito melhores para o problema Ramsey bipartido (um problema bem difícil) utilizando as construções descritas no artigo. Também apresentamos resultados originais para melhorar tais construções. Tais idéias são inspiradas no trabalho de Anup Rao (2005) e utilizam o recente êxito de Jean Bourgain (2005) em obter extratores que quebram a "barreira 1/2".', '1', 'Kohayakawa, Yoshiharu', 'aleatoriedade, algoritmos, combinatória, complexidade computacional, desaleatorização, pseudoaleatoriedade, teoria aditiva dos números', 'Ciência da Computação');

call addDissertacao('Desempenho de sistemas com dados georeplicados com consistência em momento indeterminado e na linha do tempo', '1', '1', '2013', 'Mauricio José de Oliveira de Diana', 'Sistemas web de larga escala são distribuídos em milhares de servidores em múltiplos centros de processamento de dados em diferentes localizações geográficas, operando sobre redes de longa distância (WANs). Várias técnicas são usadas para atingir os altos níveis de escalabilidade requeridos por esses sistemas. Replicação de dados está entre as principais delas, e tem por objetivo diminuir a latência, aumentar a vazão e/ou aumentar a disponibilidade do sistema. O principal problema do uso de replicação em sistemas georeplicados é a dificuldade de garantir consistência entre as réplicas sem prejudicar consideravelmente o desempenho e a disponibilidade do sistema. O desempenho do sistema é afetado pelas latências da ordem de centenas de milissegundos da WAN, enquanto a disponibilidade é afetada por falhas que impedem a comunicação entre as réplicas. Quanto mais rígido o modelo de consistência de um sistema de armazenamento, mais simples é o desenvolvimento do sistema que o usa, mas menores são seu desempenho e disponibilidade. Entre os modelos de consistência mais relaxados e mais difundidos em sistemas web georeplicados está a consistência em momento indeterminado (eventual consistency). Esse modelo de consistência garante que em algum momento as réplicas convergem após as escritas terem cessado. Um modelo mais rígido e menos difundido é a consistência na linha do tempo. Esse modelo de consistência usa uma réplica mestre para garantir que não ocorram conflitos na escrita. Nas leituras, os clientes podem ler os valores mais recentes a partir da cópia mestre, ou optar explicitamente por ler valores possivelmente desatualizados para obter maior desempenho ou disponibilidade. A consistência na linha do tempo apresenta disponibilidade menor que a consistência em momento indeterminado em determinadas situações, mas não há dados comparando o desempenho de ambas. O objetivo principal deste trabalho foi a comparação do desempenho de sistemas de armazenamento georeplicados usando esses dois modelos de consistência. Para cada modelo de consistência, foram realizados experimentos que mediram o tempo de resposta do sistema sob diferentes cargas de trabalho e diferentes condições de rede entre centros de processamento de dados. O estudo mostra que um sistema usando consistência na linha do tempo apresenta desempenho semelhante ao mesmo sistema usando consistência em momento indeterminado em uma WAN quando a localidade dos acessos é alta. Esse comparativo pode auxiliar desenvolvedores e administradores de sistemas no planejamento de capacidade e de desenvolvimento de sistemas georeplicados.', '1', 'Gerosa, Marco Aurélio', 'análise de desempenho, modelos de consistência, sistemas distribuídos, sistemas web de larga escala', 'Ciência da Computação');

call addDissertacao('Ambiente integrado para verificação e teste da coordenação de componentes tolerantes a falhas', '1', '1', '2010', 'Simone Hanazumi', 'Hoje, diante das contínuas mudanças e do mercado competitivo, as empresas e organizações têm sempre a necessidade de adaptar suas práticas de negócios para atender às diferentes exigências de seus clientes e manter-se em vantagem com relação às suas concorrentes. Para ajudá-las a atingir esta meta, uma proposta promissora é o Desenvolvimento Baseado em Componentes (DBC), cuja ideia básica é a de que um novo software possa ser construído rapidamente a partir de componentes pré-existentes. Entretanto, a montagem de sistemas corporativos mais confiáveis e tolerantes a falhas a partir da integração de componentes tem-se mostrado uma tarefa relativamente complexa. E a necessidade de garantir que tal integração não falhe tornou-se algo imprescindível, sobretudo porque as consequências de uma falha podem ser extremamente graves. Para que haja uma certa garantia de que o software seja tolerante a falhas, devem ser realizadas atividades de testes e verificação formal de programas. Isto porque ambas, em conjunto, procuram garantir ao desenvolvedor que o sistema resultante da integração é, de fato, confiável. Mas a viabilidade prática de execução destas atividades depende de ferramentas que auxiliem sua realização, uma vez que a execução de ambas constitui um alto custo para o desenvolvimento do software. Tendo em vista esta necessidade de facilitar a realização de testes e verificação nos sistemas baseados em componentes (DBC), este trabalho de Mestrado se propõe a desenvolver um ambiente integrado para a verificação e teste de protocolos para a coordenação do comportamento excepcional de componentes.', '1', 'Melo, Ana Cristina Vieira de ', 'Coordenação de Componentes, Testes, Verificação Formal', 'Ciência da Computação');

